### PR TITLE
Draft: Implement xml parsing for rpm filelist

### PR DESCRIPTION
**Pull request by windowsboy111**

### CODE REVIEW

**Comment by dralley** [comment]
Hey, I'm not sure if you're aware of this, I have a library for parsing RPM repository metadata that already works quite well

https://github.com/dralley/rpmrepo_metadata/

**Comment by windowsboy111** [comment]
Ok so apparently `FilelistXml` exists and I somehow didn't find it. I was probably blind.

Looking into it, thanks ×2.

**Comment by dralley** [comment]
@windowsboy111 Out of curiosity, *just* filelists or both primary.xml and filelists.xml?  There's a couple different ways to do it, I have a streaming API which is nice to use but currently requires that you parse all 3 files (those two + other.xml), but one of my plans was to make it possible to require less.

**Comment by korewaChino** [comment]
Andaman is no longer a package manager, we probably don't need this anymore.

**Comment by dralley** [comment]
Parsing, probably.  Are you still writing metadata?

> Full repository composition

**Comment by lleyton** [comment]
That would probably be in the scope of [subatomic](https://github.com/FyraLabs/subatomic) now, since it handles repository management outside of anda. Currently, we run `createrepo_c` to generate the repo metadata, although we'd like to move away from this because AFAIK it requires a local folder to walk through, preventing us from using S3 for repo storage. However, subatomic is written in Go, which might make it tricky to use [rpmrepo_metadata](https://github.com/dralley/rpmrepo_metadata/).

**Pull request closed without merging**
